# Generated by Django 3.2.9 on 2021-12-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.FileField(default='media/default.jpg', upload_to='media/images'),
        ),
    ]
