# Generated by Django 3.2.9 on 2021-12-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_cover',
            field=models.FileField(default='media/defaults.jpg', upload_to='media/images'),
        ),
    ]
