# Generated by Django 3.2.9 on 2021-12-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=10)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_logo', models.FileField(default='media/defaults.jpg', upload_to='media/images')),
                ('user_cover', models.FileField(default='media/default.jpg', upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.user')),
            ],
        ),
        migrations.CreateModel(
            name='postlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('jobpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobpost')),
            ],
        ),
    ]
