# Generated by Django 3.2.9 on 2021-12-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_postlike_ruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='jobpost_id',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='jobpost',
        ),
        migrations.DeleteModel(
            name='postlike',
        ),
        migrations.DeleteModel(
            name='Ruser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
