# Generated by Django 3.2.9 on 2021-12-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_auto_20211223_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=10)),
                ('job_description', models.TextField()),
                ('job_salary', models.IntegerField()),
                ('job_requirement', models.IntegerField()),
                ('job_tags', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=10)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_logo', models.FileField(default='media/defaults.jpg', upload_to='media/images')),
                ('user_cover', models.FileField(default='media/default.jpg', upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.user')),
            ],
        ),
        migrations.CreateModel(
            name='postlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ruser')),
                ('jobpost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobpost')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.user', unique=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=20)),
                ('company_contact', models.IntegerField(max_length=10)),
                ('company_city', models.CharField(max_length=20)),
                ('company_type', models.CharField(max_length=20)),
                ('company_established', models.CharField(default='', max_length=100)),
                ('company_info', models.TextField(blank=True, null=True)),
                ('company_employee', models.IntegerField(default=0)),
                ('company_logo', models.FileField(default='media/default.jpg', upload_to='media/images')),
                ('company_cover', models.FileField(default='media/defaults.jpg', upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.user')),
            ],
        ),
    ]
