# Generated by Django 3.2.9 on 2021-12-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_salary',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', unique=True),
        ),
    ]
