# Generated by Django 3.2.9 on 2021-12-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20211224_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='user_id',
            new_name='company_id',
        ),
    ]
