# Generated by Django 3.2.9 on 2022-01-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_user_id_jobpost_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
