# Generated by Django 3.2.9 on 2022-01-11 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_jobpost_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruser',
            name='user_cover',
            field=models.FileField(default='media/ucover.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='ruser',
            name='user_logo',
            field=models.FileField(default='media/ulogo.jpg', upload_to='media/images'),
        ),
        migrations.CreateModel(
            name='upost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_overview', models.TextField()),
                ('u_role', models.CharField(max_length=10)),
                ('u_language', models.CharField(max_length=10)),
                ('u_education', models.CharField(max_length=10)),
                ('u_location', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ruser')),
            ],
        ),
    ]
